version: '3.8'

services:
  graphql-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENWEATHER_API_KEY=73062d948a64deda103f2812d4ddc7fd
      - ALPHA_VANTAGE_API_KEY=66LA8M2XG3BAMHRS
    volumes:
      - .:/app
    restart: unless-stopped
