version: '3.8'

services:
  graphql-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
